###############################################
# CREATE SHORTCUT ENV VAR FOR CONF PATHS      #
###############################################

# Path to your oh-my-zsh installation.
# DTF -> Dotfiles
# OMZ -> oh-my-zsh
export DTF_ROOT="$HOME/dotfiles"
export OMZ_ROOT="$DTF_ROOT/zsh/oh-my-zsh"
export ZSH_ROOT="$DTF_ROOT/zsh"
export VIM_ROOT="$DTF_ROOT/vim"
export TMUX_PRO_PATH="$DTF_ROOT/tmux/launchers"

################
# GENERAL CONF #
################

export EDITOR="vim"

########################################################
# GRAPHIC CHANGES                                      #
########################################################

export ZSH_THEME="sunrise"
# You may need to manually set your language environment
export LANG=en_US.UTF-8

##############################################################
# IMPORT OH MY ZSH                                           #
##############################################################

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
)

source $OMZ_ROOT/oh-my-zsh.sh

###########################################################
# PLUGIN PRINT ALIAS CONFIG                               #
###########################################################

# export PRINT_ALIAS_PREFIX='  └─> ' # NON EMOJI VERSION
export PRINT_ALIAS_PREFIX='  ➡️  '
export PRINT_ALIAS_FORMAT=$'\e[1m'
export PRINT_NON_ALIAS_FORMAT=$'\e[0m'

export PRINT_ALIAS_IGNORE_REDEFINED_COMMANDS=true
export PRINT_ALIAS_IGNORE_ALIASES=(my_alias my_other_alias)
source $ZSH_ROOT/print-alias/print-alias.plugin.zsh

##############################################
# PATH CONCATENATIONS                        #
##############################################

# Add brew binaries for MACOSX
export PATH=$HOME/.brew/bin:$PATH

# Add python binaries
export PATH=$HOME/Library/Python/3.7/bin:$PATH

# Add cargo binaries
export PATH=$HOME/.cargo/bin:$PATH

# Add flutter binaries
export PATH=$HOME/flutter/bin:$PATH

##################################
# IMPORT MY OTHER CONFIGURATIONS #
##################################

source $ZSH_ROOT/src/aliases.conf

#  🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀  #

[ -z "$TMUX"  ] && { tmux attach || exec tmux new-session && exit;}

# That's better to start from home

cd ~
